### PR TITLE
New addresses for release 15 Feb

### PR DESCRIPTION
**Pull request by candida-d**
Is there any value in keeping Vega IDs in here - are they of any use to anyone?

### CODE REVIEW

**Review by edd — APPROVED** [review]

**Comment by edd** [comment]
@candida-d I’m going to poke @C0deMunk33 to ask if he’s fine to remove them from here, but I have approved this PR as right is better than wrong even in potentially redundant docs

**Comment by C0deMunk33** [comment]
@jeremyletang Will anyone ever need to know the Vega asset ID?

**Comment by edd** [comment]
> @jeremyletang Will anyone ever need to know the Vega asset ID?

If they do, they can get them through the APIs. @candida-d - remove them.

**Comment by jeremyletang** [comment]
> @jeremyletang Will anyone ever need to know the Vega asset ID?

Yes I suppose people can use the API it'll be enough.

**Review by edd — APPROVED** [review]

**Pull request merged**
